## Librerias

In [ ]:
try:
    import pandas as pd
except ImportError:
    print("Pandas not installed")
    %pip install pandas --user

try:
    import matplotlib.pyplot as plt
except ImportError:
    print("Matplotlib not installed")
    %pip install matplotlib --user

import ssl

ssl._create_default_https_context = ssl._create_unverified_context

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

## Lectura de datos

- [Dataset Qatar 2022: https://www.kaggle.com/datasets/shrikrishnaparab/fifa-world-cup-2022-qatar-match-data](https://www.kaggle.com/datasets/shrikrishnaparab/fifa-world-cup-2022-qatar-match-data)

In [ ]:
archivo = "https://raw.githubusercontent.com/IgnacioPardo/Tecnologias_Exponenciales_2025/refs/heads/main/qatar.csv"

# Leer datos del archivo
mundial : pd.DataFrame = pd.read_csv(archivo)
mundial

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
0,1,Sun,20-Nov-22,17:00,Al Bayt Stadium,Daniele Orsato,Group A,QATAR,ECUADOR,67372,...,0,1,6,5,0,0,52,72,256,279
1,2,Mon,21-Nov-22,14:00,Khalifa International Stadium,Raphael Claus,Group B,ENGLAND,IRAN,45334,...,0,1,8,13,0,0,63,72,139,416
2,3,Mon,21-Nov-22,17:00,Al Thumama Stadium,Wilton Sampaio,Group A,SENEGAL,NETHERLANDS,41721,...,0,0,9,15,0,0,63,73,263,251
3,4,Mon,21-Nov-22,20:00,Ahmed bin Ali Stadium,Abdulrahman Ibrahim Al Jassim,Group B,UNITED STATES,WALES,43418,...,0,1,7,7,0,0,81,72,242,292
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,60,Sat,10-Dec-22,20:00,Al Bayt Stadium,Wilton Sampaio,Quarter-final,ENGLAND,FRANCE,68895,...,1,0,9,15,0,0,49,54,193,308
60,61,Tue,13-Dec-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Semi-Final,ARGENTINA,CROATIA,88966,...,1,0,12,10,0,0,85,63,321,260
61,62,Wed,14-Dec-22,20:00,Al Bayt Stadium,Cesar Ramos,Semi-Final,FRANCE,MOROCCO,68294,...,0,0,13,14,0,0,72,47,328,218
62,63,Sat,17-Dec-22,16:00,Khalifa International Stadium,Abdulrahman Ibrahim Al Jassim,Play-off for third place,CROATIA,MOROCCO,44137,...,0,0,7,14,0,0,75,72,288,277
63,64,Sun,18-Dec-22,16:00,Lusail Iconic Stadium,Szymon Marciniak,Final,ARGENTINA,FRANCE,88966,...,1,2,11,21,0,0,87,104,280,409

In [ ]:
# Cuantos partidos se jugaron?
# Completar
partidos = mundial["match_no"].sum()
partidos

np.int64(2080)

In [ ]:
# Que datos tiene el dataset? (Pista: usar .info(), .describe(), .columns, .head())
# Checkear columnas
# Completar
mundial.info()
mundial.describe()
mundial.columns
mundial.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 59 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   match_no                         64 non-null     int64
 1   day_of_week                      64 non-null     object
 2   date                             64 non-null     object
 3   hour                             64 non-null     object
 4   venue                            64 non-null     object
 5   referee                          64 non-null     object
 6   group                            64 non-null     object
 7   1                                64 non-null     object
 8   2                                64 non-null     object
 9   attendance                       64 non-null     int64
 10  1_xg                             64 non-null     float64
 11  2_xg                             64 non-null     float64
 12  1_poss                           64 non-null     int64
 13  2_poss                           64 non-null     int64
 14  1_goals                          64 non-null     int64
 15  2_goals                          64 non-null     int64
 16  score                            64 non-null     object
 17  1_attempts                       64 non-null     int64
 18  2_attempts                       64 non-null     int64
 19  1_conceded                       64 non-null     int64
 20  2_conceded                       64 non-null     int64
 21  1_goal_inside_penalty_area       64 non-null     int64
 22  2_goal_inside_penalty_area       64 non-null     int64
 23  1_goal_outside_penalty_area      64 non-null     int64
 24  2_goal_outside_penalty_area      64 non-null     int64
 25  1_ontarget                       64 non-null     int64
 26  2_ontarget                       64 non-null     int64
 27  1_offtarget                      64 non-null     int64
 28  2_offtarget                      64 non-null     int64
 29  1_attempts_inside_penalty_area   64 non-null     int64
 30  2_attempts_inside_penalty_area   64 non-null     int64
 31  1_attempts_outside_penalty_area  64 non-null     int64
 32  2_attempts_outside_penalty_area  64 non-null     int64
 33  1_yellow_cards                   64 non-null     int64
 34  2_yellow_cards                   64 non-null     int64
 35  1_red_cards                      64 non-null     int64
 36  2_red_cards                      64 non-null     int64
 37  faul_against_1                   64 non-null     int64
 38  faul_against_2                   64 non-null     int64
 39  1_offsides                       64 non-null     int64
 40  2_offsides                       64 non-null     int64
 41  1_passes                         64 non-null     int64
 42  2_passes                         64 non-null     int64
 43  1_passes_compeletd               64 non-null     int64
 44  2_passes_compeletd               64 non-null     int64
 45  1_corners                        64 non-null     int64
 46  2_corners                        64 non-null     int64
 47  1_free_kicks                     64 non-null     int64
 48  2_free_kicks                     64 non-null     int64
 49  1_panelties_scored               64 non-null     int64
 50  2_panelties_scored               64 non-null     int64
 51  1_goal_prevented                 64 non-null     int64
 52  2_goal_prevented                 64 non-null     int64
 53  1_own_goal                       64 non-null     int64
 54  2_own_goal                       64 non-null     int64
 55  1_forced_turnovers               64 non-null     int64
 56  2_forced_turnovers               64 non-null     int64
 57  1_defensive_pressure_applied     64 non-null     int64
 58  2_defensive_pressure_applied     64 non-null     int64
dtypes: float64(2), int64(48), object(9)
memory usage: 29.6+ KB

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
0,1,Sun,20-Nov-22,17:00,Al Bayt Stadium,Daniele Orsato,Group A,QATAR,ECUADOR,67372,...,0,1,6,5,0,0,52,72,256,279
1,2,Mon,21-Nov-22,14:00,Khalifa International Stadium,Raphael Claus,Group B,ENGLAND,IRAN,45334,...,0,1,8,13,0,0,63,72,139,416
2,3,Mon,21-Nov-22,17:00,Al Thumama Stadium,Wilton Sampaio,Group A,SENEGAL,NETHERLANDS,41721,...,0,0,9,15,0,0,63,73,263,251
3,4,Mon,21-Nov-22,20:00,Ahmed bin Ali Stadium,Abdulrahman Ibrahim Al Jassim,Group B,UNITED STATES,WALES,43418,...,0,1,7,7,0,0,81,72,242,292
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361

## Analisis

### Primera Parte

In [ ]:
# Cuantas selecciones participaron?
# Completar
selecciones = pd.concat([mundial['1'], mundial['2']]).unique().size
selecciones

32

In [ ]:
# Cuantas fases tiene el mundial?
# Completar

fases = mundial['group'].unique()
fases_totales = len(fases) # len() nos da la cantidad de elementos en el array de fases únicas
fases = fases_totales
fases

In [ ]:
# Cual fue la "attendance" promedio por partido?
# Completar
promedio = mundial['attendance'].mean()
promedio

np.float64(53191.4375)

In [ ]:
# Cual fue el partido con mas diferencia de goles?
# Completar
columnas_selecciones= ["1","2"]
mundial.loc[(mundial["1_goals"]- mundial["2_goals"]).abs().idxmax(), columnas_selecciones]

1         SPAIN
2    COSTA RICA
Name: 10, dtype: object

In [ ]:
# Cual es la selección que mas penales metió?
# Completar

penales1 = mundial.groupby('1')['1_panelties_scored'].sum()
penales2 = mundial.groupby('2')['2_panelties_scored'].sum()
penales = pd.concat([penales1, penales2]).groupby(level=0).sum()
penales.idxmax()

'ARGENTINA'

In [ ]:
# Cual es la selección que mas penales le hicieron?
# Completar
penales1 = mundial.groupby('1')['1_panelties_scored'].sum()
penales2 = mundial.groupby('2')['2_panelties_scored'].sum()
penales = pd.concat([penales1, penales2]).groupby(level=0).sum()
penales.idxmin()

'AUSTRALIA'

### Segunda Parte

In [ ]:
equipo : str = "ARGENTINA"

In [ ]:
# Seleccionar todos los partidos que jugo el equipo de "local"
# Completar

filtroLocal : pd.Series = mundial['1'] == equipo
partidos_local = mundial[filtroLocal]
partidos_local

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361
23,24,Sat,26-Nov-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Group C,ARGENTINA,MEXICO,88966,...,0,0,4,5,0,0,63,79,220,327
49,50,Sat,3-Dec-22,20:00,Ahmed bin Ali Stadium,Szymon Marciniak,Round of 16,ARGENTINA,AUSTRALIA,45032,...,0,0,5,14,1,0,67,73,240,453
60,61,Tue,13-Dec-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Semi-Final,ARGENTINA,CROATIA,88966,...,1,0,12,10,0,0,85,63,321,260
63,64,Sun,18-Dec-22,16:00,Lusail Iconic Stadium,Szymon Marciniak,Final,ARGENTINA,FRANCE,88966,...,1,2,11,21,0,0,87,104,280,409

In [ ]:
# Seleccionar todos los partidos que jugo el equipo de "visitante"
# Completar

filtroVisitante : pd.Series = mundial['2'] == equipo
partidos_visitante = mundial[filtroVisitante]
partidos_visitante

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
38,39,Wed,30-Nov-22,20:00,Lusail Iconic Stadium,Michael Oliver,Group C,POLAND,ARGENTINA,84985,...,0,0,25,4,0,0,67,48,438,141
57,58,Fri,9-Dec-22,20:00,Lusail Iconic Stadium,Antonio Mateu Lahoz,Quarter-final,NETHERLANDS,ARGENTINA,88235,...,0,1,15,5,0,0,91,79,401,323

In [ ]:
# Seleccionar todos los partidos que jugo el equipo (de "local" o "visitante")
# Completar

partidos : pd.DataFrame = pd.concat([partidos_local, partidos_visitante])
partidos

,match_no,day_of_week,date,hour,venue,referee,group,1,2,attendance,...,1_panelties_scored,2_panelties_scored,1_goal_prevented,2_goal_prevented,1_own_goal,2_own_goal,1_forced_turnovers,2_forced_turnovers,1_defensive_pressure_applied,2_defensive_pressure_applied
4,5,Tue,22-Nov-22,11:00,Lusail Iconic Stadium,Slavko Vincic,Group C,ARGENTINA,SAUDI ARABIA,88012,...,1,0,4,14,0,0,65,80,163,361
23,24,Sat,26-Nov-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Group C,ARGENTINA,MEXICO,88966,...,0,0,4,5,0,0,63,79,220,327
49,50,Sat,3-Dec-22,20:00,Ahmed bin Ali Stadium,Szymon Marciniak,Round of 16,ARGENTINA,AUSTRALIA,45032,...,0,0,5,14,1,0,67,73,240,453
60,61,Tue,13-Dec-22,20:00,Lusail Iconic Stadium,Daniele Orsato,Semi-Final,ARGENTINA,CROATIA,88966,...,1,0,12,10,0,0,85,63,321,260
63,64,Sun,18-Dec-22,16:00,Lusail Iconic Stadium,Szymon Marciniak,Final,ARGENTINA,FRANCE,88966,...,1,2,11,21,0,0,87,104,280,409
38,39,Wed,30-Nov-22,20:00,Lusail Iconic Stadium,Michael Oliver,Group C,POLAND,ARGENTINA,84985,...,0,0,25,4,0,0,67,48,438,141
57,58,Fri,9-Dec-22,20:00,Lusail Iconic Stadium,Antonio Mateu Lahoz,Quarter-final,NETHERLANDS,ARGENTINA,88235,...,0,1,15,5,0,0,91,79,401,323

In [ ]:
# Cuantos goles hizo el equipo en total (obtener los goles metidos de local y sumarlos con los goles metidos de visitante)
# Completar

goles : int = partidos['1_goals'].sum() + partidos['2_goals'].sum()
goles

np.int64(23)

In [62]:
# Cuantos goles hizo el equipo en promedio
# Completar

promedio_goles : int = goles / len(partidos)
promedio_goles

np.float64(3.2857142857142856)

In [68]:
ganados : int = (partidos_local['1_goals'] > partidos_local['2_goals']).sum() + \
               (partidos_visitante['2_goals'] > partidos_visitante['1_goals']).sum()
ganados

np.int64(4)

In [ ]:
# Graficar los goles hechos por el equipo en cada partido

fig, ax = plt.subplots()
# Completar

### Tercera Parte

In [ ]:
# Contar cuantos goles hizo cada equipo en total en el mundial
# Completar

equipos =
goles =

In [ ]:
# Graficar los goles por equipo en todo el mundial

fig, ax = plt.subplots()
# Completar

In [ ]:
# Cual es el equipo que hizo mas goles en el mundial?
# Completar

In [ ]:
# Por cada partido, cual fue la diferencia de goles?
# Completar

In [ ]:
# Por cada partido, cual fue el equipo que gano?
# Completar

In [ ]:
# En cada fase del mundial, cual fue el equipo que hizo mas goles?
# Completar

### Tercera Parte

In [ ]:
# Armar un gráfico a partir de algun nuevo análisis que se te ocurra
# Completar